### ISSUE TITLE
IOS :  didUpdateRatio:ratio error

### ISSUE THREAD

**Issue by celinevia** [cisclub/react-native-teads#3]
Hello,

I use your Library to add teads in android and ios. But ios it donesn't work.
I have this issue in code:
 Thread 1: Exception: "-[RNTTeadsInReadAdViewManager didUpdateRatio:ratio:]: unrecognized selector sent to instance 0x28373c820"

and this issue in app :  
![2020-10-05](https://user-images.githubusercontent.com/72379154/95054911-dc21ff80-06f2-11eb-9deb-190d32f66f04.png)

Can you tell me if i make something false?
My code :
```
<TeadsNativeAdView
     style={[
     {
           width:this.state.width,
           height: this.state.height,
       }]}
       pid={Platform.OS==="ios"? teadsIOSId:teadsAndroidId }
       onDidReceiveAd={this.onDidReceiveAd}
       onAdDidFail ={(err)=>{
            console.log("onAdDidFail",err)
       }}
       onAdError={(err)=>{
           console.log("onAdError",err)
       }}
/>

**Comment by Arlien** [comment]
This issue is fixed on this fork : https://github.com/DevOneFactory/react-native-teads
